"""update partner profile model

Revision ID: 779771aadd63
Revises: dd4e1f486397
Create Date: 2026-08-14 14:04:05.515380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '779771aadd63'
down_revision = 'dd4e1f486397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('partner_type', sa.String(length=30), nullable=False))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('specialty',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.drop_column('clinic_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinic_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('specialty',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.drop_column('partner_type')
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###
