"""add clients prescriptions and orders

Revision ID: a8f19de16aac
Revises: bd5f66e94c12
Create Date: 2026-09-28 19:34:34.814113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f19de16aac'
down_revision = 'bd5f66e94c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_number', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_client_number'), ['client_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_clients_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_phone'), ['phone'], unique=False)

    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('right_sph', sa.String(length=20), nullable=True),
    sa.Column('right_cyl', sa.String(length=20), nullable=True),
    sa.Column('right_axis', sa.String(length=20), nullable=True),
    sa.Column('right_add', sa.String(length=20), nullable=True),
    sa.Column('right_pd', sa.String(length=20), nullable=True),
    sa.Column('left_sph', sa.String(length=20), nullable=True),
    sa.Column('left_cyl', sa.String(length=20), nullable=True),
    sa.Column('left_axis', sa.String(length=20), nullable=True),
    sa.Column('left_add', sa.String(length=20), nullable=True),
    sa.Column('left_pd', sa.String(length=20), nullable=True),
    sa.Column('prescription_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescriptions_client_id'), ['client_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=30), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('frame_make', sa.String(length=150), nullable=True),
    sa.Column('frame_model', sa.String(length=150), nullable=True),
    sa.Column('frame_size', sa.String(length=100), nullable=True),
    sa.Column('tint_color', sa.String(length=150), nullable=True),
    sa.Column('lens_type', sa.String(length=150), nullable=True),
    sa.Column('coating', sa.String(length=150), nullable=True),
    sa.Column('base_curve', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_prescription_id'), ['prescription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_prescription_id'))
        batch_op.drop_index(batch_op.f('ix_orders_partner_id'))
        batch_op.drop_index(batch_op.f('ix_orders_order_number'))
        batch_op.drop_index(batch_op.f('ix_orders_client_id'))

    op.drop_table('orders')
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescriptions_client_id'))

    op.drop_table('prescriptions')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_phone'))
        batch_op.drop_index(batch_op.f('ix_clients_email'))
        batch_op.drop_index(batch_op.f('ix_clients_client_number'))

    op.drop_table('clients')
    # ### end Alembic commands ###
